name: Interni LaTeX document
on: 
  push:    
    paths:
      - 'interni/**'
      - '.github/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2            
            
      - name: Compile "interni" documents
        uses: xu-cheng/texlive-action/full@v1
        with:
          #Mi sposto nella cartella "interni/verbali" e mi prendo la lista delle sottocartelle
          #Successivamente compilo i main.tex di ogni sottocartella
          run: |
            cd interni/verbali
            for d in */ ; do
                latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd ${d}main.tex
            done
            
            
      - name: Notify Discord if failure
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.BUILD_FAILURE_WEBHOOK }}
          title: "Latex Interni"
          color: 0xff0000
          username: GitHub Actions
            
