name: LaTeX documents
on: 
  push:    
    paths:
      - 'interni/**'
      - 'esterni/**'
      - '.github/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag danteev/texlive:latest

      - name: Search and Compiling Latex Files
        uses: ToldoDM/Latex-multicompiler@1
        with:
          path_to_list: .github/filesToCompile


      - name: Notify Discord if failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.BUILD_FAILURE_WEBHOOK }}
          title: "Documenti Latex"
          color: 0xff0000
          username: GitHub Actions
