name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile "template" documents
        uses: xu-cheng/texlive-action/full@v1
        with:
          #Mi sposto nella cartella "template" e mi prendo la lista delle sottocartelle
          #Successivamente compilo i main.tex di ogni sottocartella
          run: |
            cd template
            for d in */ ; do
                latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd ${d}main.tex
            done
      - name: Compile "interni" documents
        uses: xu-cheng/texlive-action/full@v1
        with:
          #Mi sposto nella cartella "Verbali-riunioni" e mi prendo la lista delle sottocartelle
          #Successivamente compilo i main.tex di ogni sottocartella
          run: |
            cd interni/verbali
            for d in */ ; do
                latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd ${d}main.tex
            done
