name: Templates LaTeX Document
on: 
  push:    
    paths:
      - 'template/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile "template" documents
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd template/documenti/main.tex     
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd template/lettera/main.tex
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd template/verbale_e-mail/main.tex
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -cd template/verbale_riunione/main.tex          
            
      - name: Notify Discord if failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.BUILD_FAILURE_WEBHOOK }}
          title: "Latex Template"
          color: 0xff0000
          username: GitHub Actions
            
